POST http://localhost:8000/api/auth/register

{
    "name": "John Doe",
    "email": "gugadanielalvez@gmail.com",
    "password": "adcde12345#"
}

###
POST http://localhost:8000/api/auth/login

{
    "email": "johndoe@example.com",
    "password": "adcde12345#"
}