POST http://localhost:8000/api/auth/login

{
    "email": "gustavo@gmail.com",
    "password": "Rg54757185#"
}

###
POST http://localhost:8000/api/auth/register

{
    "name": "Gustavo",
    "email": "gustavo@gmail.com",
    "password": "Rg54757185#"
}