POST http://localhost:8080/api/auth/login

{
    "email": "gustavo@gmail.com",
    "password": "Rg54757185"
}

###
POST http://localhost:8080/api/auth/register

{
    "name": "Gustavo",
    "email": "gustavo@gmail.com",
    "password": "Rg54757185"
}