GET http://localhost:8080/api/product?limit=30&page=1&orderBy=name&ordination=asc
Authorization: Bearer v2.local.2iyAOiAVchdTh2Z-_U_yS8rastAKUbLBFyPZ81T2RLnrlkWwuDfJntuyG0sRProBySfg4LtgUtXfG4wy_GEVPyaFWuel4cHkc_wdjatKLuhEz0OmxKshJYHONNu_6fFaRjxqjGYuO9AhQ70yglhPhNg2GfeWLdU8bTKAgr4pz4OOaQH7gsfrm54lIlvxKxZMdHjwJWoSbxfeuLv7wJQxlkG0wF8_JM9K8Z3C9wP-6HjvCzkmEQ_d0q_T9hsosNRHbQBRF6KvdWiyE7IjYgugDYvEL780U2P8ljZu2_iH.eyJleHBpcmVzX2F0IjoiMjAyNi0wMy0yMlQwMDoyODo0Ny4yMzEwMjcyWiJ9