ServerSettings:
  Port: 8000
  Host: "localhost"
  Domain: "http://localhost:8000"

RepositorySettings:
  Host: localhost
  Port: 3306
  Name: "sprinter_db"
  User: "root"
  Password: "root"

EnvironmentSettings:
  EnvironmentType: "development"

LogSettings:
  LogDir: "./runtime/logs"

PasetoSettings:
  PasetoSecurityKey: "b7e16bf2-ab0f-4a68-a16b-f2ab0f6a"

FileStorageSettings:
  StorageFolder: "./runtime/storage"

SMTPSettings:
  Host: ""
  Port: ""
  User: ""
  Password: ""
  From: ""