ServerSettings:
  Port: 8000
  Host: "localhost"
  Domain: "http://localhost:8000"

ServiceConfig:
  Name: "sprinter_server"
  Display: "Sprinter Web Service"
  Description: "Sprinter Web Service"

RepositorySettings:
  Host: localhost
  Port: 3306
  Name: "sprinter_db"
  User: "root"
  Password: "root"

EnvironmentSettings:
  EnvironmentType: "development"

LogSettings:
  LogDir: "./runtime/logs"

PasetoSettings:
  PasetoSecurityKey: "ldJfKJMxCMSxQWpjkWRjUPUjdzlbQVdU"

CORSConfig:
  CORSOrigins:
    - "localhost:8000"

FileStorageSettings:
  StorageFolder: "./runtime/storage"

SMTPSettings:
  Host: "localhost"
  Port: 1025
  User: "Sprinter"
  Password: "ytlLhqKiVwCgObHZTpzZRSYFVSBRQdOA"
  From: "no-reply@spinter.com"
  MaxConnections: 5
  IdleTimeout: 30s
  PoolWaitTimeout: 10s