Environment = "development"

[Server]
Port = 8000
Host = "localhost"
Domain = "http://localhost:8000"

[RepositorySettings]
Host = "localhost"
Port = "3306"
Name = "sprinter_db"
User = "root"
Password = "root"

[LogSettings]
LogDir = "./runtime/logs"

[Paseto]
PasetoSecurityKey = "b7e16bf2-ab0f-4a68-a16b-f2ab0f6a"

[StorageSettings]
StorageFolder = "./runtime/storage"

[SMTPConfig]
Host = ""
Port = ""
User = ""
Password = ""
From = ""